AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/ClassLength:
  Enabled: true
  Max: 150

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - x
    - y

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120
