require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'benchmarks/definitions/*'
    - 'tmp/**/*'
  NewCops: enable
  TargetRubyVersion: 3.3

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - id
    - up
    - x
    - y

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
