AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Lint/EmptyClass:
  Enabled: true
  AllowComments: true

Metrics/ClassLength:
  Enabled: true
  Max: 500

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - up
    - x
    - y

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120
